# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starproject', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starproject.Profile'),
        ),
    ]
